name: Create LLVM Binary Releases

on:
  workflow_dispatch:
    inputs:
      binary_url:
        description: 'URL to the LLVM binary tar file'
        required: true
        type: string

permissions:
  contents: write  # Required for creating releases

jobs:
  extract-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Extract binaries
        run: |
          # Create a clean directory for release artifacts
          mkdir -p release_artifacts
          
          # Extract binaries to output dir
          python scripts/process_binary.py \
            -o ./output \
            "${{ github.event.inputs.binary_url }}"
          
          # Move only the binaries and metadata to release directory
          mv output/* release_artifacts/

      - name: Read metadata
        id: meta
        run: |
          # Get release tag
          echo "tag=$(jq -r .release_tag ./release_artifacts/metadata.json)" >> $GITHUB_OUTPUT
          # Get version info
          echo "version=$(jq -r .version ./release_artifacts/metadata.json)" >> $GITHUB_OUTPUT
          echo "platform=$(jq -r .platform ./release_artifacts/metadata.json)" >> $GITHUB_OUTPUT
          echo "os=$(jq -r .os ./release_artifacts/metadata.json)" >> $GITHUB_OUTPUT
          echo "date=$(jq -r .extraction_date ./release_artifacts/metadata.json)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          omitBodyDuringUpdate: true
          artifacts: "./release_artifacts/*"
          artifactErrorsFailBuild: true
          makeLatest: false
          generateReleaseNotes: false
          removeArtifacts: true
          tag: "${{ steps.meta.outputs.tag }}"
          body: |
            LLVM binaries extracted from ${{ github.event.inputs.binary_url }}
            
            Version: ${{ steps.meta.outputs.version }}
            Platform: ${{ steps.meta.outputs.platform }}
            OS: ${{ steps.meta.outputs.os }}
            
            Extraction Date: ${{ steps.meta.outputs.date }}
            Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
